name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    #- name: Test with unittest
    #  run: |
    #    python S16/test_cases.py

    #- name: Test with unittest S17 - 1
    #  run: |
    #    python S17/test_validate.py

    #- name: Test with unittest S17 - 2
    #  run: |
    #    python S17/test_merge.py

    #- name: Test with unittest S18
    #  run: |
    #    pip install marshmallow
    #    python S18/test_assignment.py

    #- name: Test with unittest S19
    #  run: |
    #    python S19/test_smart_device.py

    - name: Test with unittest S20
      run: |
 .      pip install marshmallow
        pytest --maxfail=1 --disable-warnings -q
